version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodejs-network
    volumes:
    - ./mysql/init:/docker-entrypoint-initdb.d

  app:
    build:
      context: nodejs
    image: mendesf/app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    ports:
      - "3000:3000"
    networks:
      - nodejs-network
    depends_on:
      - db
    volumes:
      - ./nodejs/app:/usr/src/app

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodejs-network
    depends_on:
      - app

networks:
  nodejs-network:
    driver: bridge
